# Exploratory Data Analysis: `all_3_questionnaire`

Source file: `all_3.csv`

This notebook performs a structured EDA: data loading, structure/dtypes, missing-value analysis, descriptive statistics, distributions, categorical breakdowns, and a correlation heatmap, finishing with a single combined dashboard figure saved as PNG.

In [1]:
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style='whitegrid', font_scale=0.8)
pd.set_option('display.max_columns', 60)
pd.set_option('display.width', 160)

dataset_name = 'all_3_questionnaire'

## 1. Load data

In [2]:
csv_path = r"/mnt/user-data/uploads/all_3.csv"
try:
    df = pd.read_csv(csv_path, low_memory=False)
except UnicodeDecodeError:
    df = pd.read_csv(csv_path, low_memory=False, encoding='latin1')

print("Shape:", df.shape)
df.head()

Shape: (10175, 953)

,SEQN,ACD011A,ACD011B,ACD011C,ACD040,ACD110,ALQ101,ALQ110,ALQ120Q,ALQ120U,ALQ130,ALQ141Q,ALQ141U,ALQ151,ALQ160,BPQ020,BPQ030,BPD035,BPQ040A,BPQ050A,BPQ056,BPD058,BPQ059,BPQ080,BPQ060,BPQ070,BPQ090D,BPQ100D,CBD070,CBD090,...,WHQ070,WHD080A,WHD080B,WHD080C,WHD080D,WHD080E,WHD080F,WHD080G,WHD080H,WHD080I,WHD080J,WHD080K,WHD080M,WHD080N,WHD080O,WHD080P,WHD080Q,WHD080R,WHD080S,WHD080T,WHD080U,WHD080L,WHD110,WHD120,WHD130,WHD140,WHQ150,WHQ030M,WHQ500,WHQ520
0,73557,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,3.0,1.0,0.0,NaN,1.0,NaN,1.0,1.0,62.0,1.0,2.0,2.0,NaN,2.0,1.0,NaN,1.0,1.0,1.0,300.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.0,270.0,200.0,69.0,270.0,62.0,NaN,NaN,NaN
1,73558,1.0,NaN,NaN,NaN,NaN,1.0,NaN,7.0,1.0,4.0,2.0,1.0,1.0,0.0,1.0,1.0,53.0,2.0,NaN,1.0,52.0,2.0,1.0,NaN,1.0,1.0,1.0,642.0,214.0,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,240.0,250.0,72.0,250.0,25.0,NaN,NaN,NaN
2,73559,1.0,NaN,NaN,NaN,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,1.0,1.0,40.0,1.0,1.0,2.0,NaN,2.0,1.0,NaN,1.0,1.0,1.0,150.0,25.0,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.0,190.0,70.0,228.0,35.0,NaN,NaN,NaN
3,73560,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,3.0
4,73561,1.0,NaN,NaN,NaN,NaN,1.0,NaN,0.0,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,55.0,1.0,1.0,1.0,12.0,2.0,2.0,1.0,1.0,2.0,NaN,200.0,0.0,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.0,135.0,67.0,170.0,60.0,NaN,NaN,NaN

## 2. Structure & data types

In [3]:
dtype_counts = df.dtypes.astype(str).value_counts()
print("Column count by dtype:")
print(dtype_counts)
print()
buf_info = []
df.info(buf=None)

Column count by dtype:
float64    944
int64        7
str          2
Name: count, dtype: int64

<class 'pandas.DataFrame'>
RangeIndex: 10175 entries, 0 to 10174
Columns: 953 entries, SEQN to WHQ520
dtypes: float64(944), int64(7), str(2)
memory usage: 74.0 MB

## 3. Missing value analysis

In [4]:
missing = df.isna().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({'missing_count': missing, 'missing_pct': missing_pct})
missing_df = missing_df[missing_df['missing_count'] > 0].sort_values('missing_pct', ascending=False)
print(f"Columns with missing values: {len(missing_df)} / {df.shape[1]}")
missing_df.head(30)

Columns with missing values: 946 / 953

          missing_count  missing_pct
SMQ690J           10175       100.00
SMQ861            10175       100.00
MCQ240I           10175       100.00
MCQ240R           10175       100.00
OSQ040BH          10174        99.99
OSD030BI          10174        99.99
OSQ040BI          10174        99.99
OSD030BH          10174        99.99
MCQ240V           10174        99.99
OSQ040BJ          10174        99.99
OSD030BJ          10174        99.99
PAQ759T           10174        99.99
OSD050CB          10174        99.99
OSD030BG          10174        99.99
OSQ040BG          10174        99.99
OSD030BE          10173        99.98
MCQ240C           10173        99.98
OSQ100G           10173        99.98
OSD110G           10173        99.98
OSQ040BF          10173        99.98
OSD030BF          10173        99.98
OSQ040AC          10173        99.98
OSD050BD          10173        99.98
OSD030AC          10173        99.98
SMQ665D           10173        99.98
MCQ240H           10173        99.98
MCQ230D           10173        99.98
OSQ090H           10173        99.98
OSQ120H           10173        99.98
OSQ040CC          10173        99.98

## 4. Descriptive statistics (numeric columns)

In [5]:
numeric_cols_all = df.select_dtypes(include=np.number).columns.tolist()
desc = df[numeric_cols_all].describe().T
desc.head(30)

           count          mean            std      min      25%      50%      75%       max
SEQN     10175.0  78644.000000    2937.413829  73557.0  76100.5  78644.0  81187.5   83731.0
ACD011A   5759.0      1.000000       0.000000      1.0      1.0      1.0      1.0       1.0
ACD011B     16.0      8.000000       0.000000      8.0      8.0      8.0      8.0       8.0
ACD011C    171.0      9.000000       0.000000      9.0      9.0      9.0      9.0       9.0
ACD040    2374.0      3.101095       1.511821      1.0      2.0      3.0      4.0       9.0
ACD110    1007.0      2.956306       1.733794      1.0      1.0      3.0      5.0       5.0
ALQ101    5421.0      1.311197       0.545023      1.0      1.0      1.0      2.0       9.0
ALQ110    1631.0      1.594727       0.615303      1.0      1.0      2.0      2.0       9.0
ALQ120Q   4479.0      4.709310      34.428362      0.0      1.0      2.0      4.0     999.0
ALQ120U   3593.0      1.921514       0.853701      1.0      1.0      2.0      3.0       3.0
ALQ130    3596.0      3.511123      28.866122      1.0      1.0      2.0      3.0     999.0
ALQ141Q   3595.0      4.065925      45.410645      0.0      0.0      0.0      2.0     999.0
ALQ141U   1464.0      2.326503       0.844722      1.0      2.0      3.0      3.0       3.0
ALQ151    4477.0      1.837168       0.385823      1.0      2.0      2.0      2.0       9.0
ALQ160    1866.0      1.224544      23.236249      0.0      0.0      0.0      0.0     999.0
BPQ020    6464.0      1.669090       0.514554      1.0      1.0      2.0      2.0       9.0
BPQ030    2174.0      1.226311       0.617529      1.0      1.0      1.0      1.0       9.0
BPD035    2164.0     58.845656     109.916154     10.0     35.0     47.0     58.0     999.0
BPQ040A   2174.0      1.171573       0.440162      1.0      1.0      1.0      1.0       9.0
BPQ050A   1815.0      1.130028       0.379544      1.0      1.0      1.0      1.0       9.0
BPQ056    6464.0      1.757890       0.448164      1.0      2.0      2.0      2.0       9.0
BPD058    1579.0    150.069031     599.215646      1.0      4.0     24.0    104.0    9999.0
BPQ059    6464.0      1.867420       0.345923      1.0      2.0      2.0      2.0       7.0
BPQ080    6464.0      1.723855       0.715436      1.0      1.0      2.0      2.0       9.0
BPQ060    4427.0      1.660267       1.472373      1.0      1.0      1.0      2.0       9.0
BPQ070    4620.0      1.616234       1.069422      1.0      1.0      1.0      2.0       9.0
BPQ090D   4620.0      1.696753       0.544243      1.0      1.0      2.0      2.0       9.0
BPQ100D   1450.0      1.235862       0.578744      1.0      1.0      1.0      1.0       9.0
CBD070   10052.0  20255.040092  138337.301040      0.0    257.0    410.5    642.0  999999.0
CBD090   10043.0  22629.867669  147786.437306      0.0      0.0      0.0     50.0  999999.0

## 5. Select representative columns for visualization

Given the potentially large number of columns, we pick the most complete (least missing) numeric columns and the most informative low-cardinality categorical columns for plotting.

In [6]:
id_like = ["SEQN"]

# Numeric columns: exclude ID-like, exclude near-constant, rank by completeness then variance
num_candidates = [c for c in numeric_cols_all if c not in id_like]
completeness = df[num_candidates].notna().mean()
nunique = df[num_candidates].nunique()
num_candidates = [c for c in num_candidates if nunique.get(c, 0) > 1]
ranked_numeric = (completeness.loc[num_candidates]).sort_values(ascending=False)
plot_numeric_cols = ranked_numeric.head(12).index.tolist()
print("Numeric columns selected for plotting:")
print(plot_numeric_cols)

# Categorical-like columns: object/string dtype OR numeric with small nunique
obj_cols = df.select_dtypes(exclude=np.number).columns.tolist()
low_card_numeric = [c for c in numeric_cols_all if c not in id_like and 2 <= df[c].nunique() <= 10]
cat_candidates = [c for c in (obj_cols + low_card_numeric) if c not in id_like]
cat_candidates = [c for c in cat_candidates if df[c].nunique() <= 15 and df[c].nunique() >= 2]
plot_cat_cols = cat_candidates[:6]
print("Categorical columns selected for plotting:")
print(plot_cat_cols)

Numeric columns selected for plotting:
['HUQ030', 'HUQ010', 'HIQ011', 'HUQ051', 'HUQ071', 'IMQ020', 'SMAQUEX.x', 'SMQ860', 'SMQ874', 'SMQ878', 'SMQ870', 'FSQ165']

Categorical columns selected for plotting:
['ACD040', 'ACD110', 'ALQ101', 'ALQ110', 'ALQ120U', 'ALQ141U']

## 6. Correlation heatmap

In [7]:
corr_cols = ranked_numeric.head(15).index.tolist()
plt.figure(figsize=(9, 7))
if len(corr_cols) >= 2:
    corr = df[corr_cols].corr()
    sns.heatmap(corr, cmap='coolwarm', center=0, annot=False, linewidths=0.3, cbar_kws={'shrink': 0.7})
    plt.title(f'Correlation heatmap ({dataset_name})')
    plt.tight_layout()
else:
    plt.text(0.5, 0.5, 'Not enough numeric columns for correlation', ha='center')
plt.show()

## 7. Distributions of key numeric variables

In [8]:
n = len(plot_numeric_cols)
ncols = 4
nrows = int(np.ceil(n / ncols)) if n else 1
fig, axes = plt.subplots(nrows, ncols, figsize=(ncols*3.5, nrows*2.8))
axes = np.array(axes).reshape(-1)
for i, c in enumerate(plot_numeric_cols):
    ax = axes[i]
    data = df[c].dropna()
    ax.hist(data, bins=30, color='#4C72B0', edgecolor='white')
    ax.set_title(c, fontsize=9)
for j in range(len(plot_numeric_cols), len(axes)):
    axes[j].axis('off')
fig.suptitle(f'Distributions of key numeric variables ({dataset_name})', y=1.02)
plt.tight_layout()
plt.show()

## 8. Categorical variable breakdowns

In [9]:
n = len(plot_cat_cols)
if n:
    ncols = 3
    nrows = int(np.ceil(n / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(ncols*4, nrows*3))
    axes = np.array(axes).reshape(-1)
    for i, c in enumerate(plot_cat_cols):
        ax = axes[i]
        vc = df[c].value_counts(dropna=True).head(10)
        sns.barplot(x=vc.values, y=vc.index.astype(str), ax=ax, color='#55A868')
        ax.set_title(c, fontsize=9)
        ax.set_xlabel('')
    for j in range(len(plot_cat_cols), len(axes)):
        axes[j].axis('off')
    fig.suptitle(f'Categorical variable breakdowns ({dataset_name})', y=1.02)
    plt.tight_layout()
    plt.show()
else:
    print('No suitable low-cardinality categorical columns found.')

## 9. Combined EDA dashboard (single PNG canvas)

All the small plots above are combined into one figure/canvas and exported as a single PNG image for this dataset.

In [10]:
png_path = r"/mnt/user-data/outputs/all_3_EDA_dashboard.png"

n_num = len(plot_numeric_cols)
n_cat = len(plot_cat_cols)
hist_rows = int(np.ceil(n_num / 4)) if n_num else 1
cat_rows = int(np.ceil(n_cat / 3)) if n_cat else 0

total_rows = 2 + hist_rows + cat_rows  # row0: missing+corr, then hist_rows, then cat_rows
fig = plt.figure(figsize=(20, 5 + hist_rows*3.2 + cat_rows*3.2))
gs = gridspec.GridSpec(1 + hist_rows + cat_rows, 4, figure=fig, hspace=0.6, wspace=0.4)

# Row 0a: missingness (spans 2 cols)
ax_miss = fig.add_subplot(gs[0, 0:2])
if len(missing_df):
    top_missing = missing_df.head(15)
    sns.barplot(x=top_missing['missing_pct'], y=top_missing.index.astype(str), ax=ax_miss, color='#C44E52')
    ax_miss.set_title('Top missing-value columns (%)', fontsize=10)
else:
    ax_miss.text(0.5, 0.5, 'No missing values', ha='center')
    ax_miss.axis('off')

# Row 0b: correlation heatmap (spans 2 cols)
ax_corr = fig.add_subplot(gs[0, 2:4])
if len(corr_cols) >= 2:
    sns.heatmap(df[corr_cols].corr(), cmap='coolwarm', center=0, ax=ax_corr, cbar_kws={'shrink': 0.6})
    ax_corr.set_title('Correlation heatmap', fontsize=10)
    ax_corr.tick_params(labelsize=6)
else:
    ax_corr.text(0.5, 0.5, 'Not enough numeric cols', ha='center')
    ax_corr.axis('off')

# Histogram grid
for i, c in enumerate(plot_numeric_cols):
    r = 1 + i // 4
    cpos = i % 4
    ax = fig.add_subplot(gs[r, cpos])
    ax.hist(df[c].dropna(), bins=25, color='#4C72B0', edgecolor='white')
    ax.set_title(c, fontsize=8)
    ax.tick_params(labelsize=6)

# Categorical grid
for i, c in enumerate(plot_cat_cols):
    r = 1 + hist_rows + i // 3
    cpos_group = i % 3
    ax = fig.add_subplot(gs[r, cpos_group])
    vc = df[c].value_counts(dropna=True).head(8)
    sns.barplot(x=vc.values, y=vc.index.astype(str), ax=ax, color='#55A868')
    ax.set_title(c, fontsize=8)
    ax.tick_params(labelsize=6)
    ax.set_xlabel('')

fig.suptitle(f'Combined EDA Dashboard — all_3_questionnaire', fontsize=16, y=1.01)
fig.savefig(png_path, dpi=150, bbox_inches='tight')
plt.show()
print('Saved combined dashboard to:', png_path)

Saved combined dashboard to: /mnt/user-data/outputs/all_3_EDA_dashboard.png

## 10. Summary

This notebook covered: dataset shape and dtypes, missingness, descriptive statistics, univariate distributions of the most complete numeric variables, categorical breakdowns of low-cardinality fields, a correlation heatmap, and a single combined dashboard PNG summarizing all of the above.